SET SERVEROUTPUT ON;
--CHANGE PASSWORD TEST;
DECLARE
PIS_PHONE       SUBSCRIBER.PHONE_NUMBER%TYPE     := '5362295555';
PIS_MAIL        SUBSCRIBER.EMAIL%TYPE            := 'ali.kose@ext.i2i-systems.com';
PIS_NEW_PASS    SUBSCRIBER.PASS_WORD%TYPE        := 'Ali123';
CHECKER NUMBER;
BEGIN
    CHANGE_PASSWORD(PIS_PHONE, PIS_MAIL, PIS_NEW_PASS, CHECKER);
END;
/


--CHECK USER TEST;
DECLARE
CHECKER NUMBER;
PIS_PHONE   SUBSCRIBER.PHONE_NUMBER%TYPE   :='5362295555';
PIS_PASS    SUBSCRIBER.PASS_WORD%TYPE      :='Ali123';
BEGIN
    CHECK_USER(PIS_PHONE, PIS_PASS, CHECKER);
END;
/

--CREATE USER TEST;
DECLARE
CHECKER         NUMBER;
PIS_F_NAME       SUBSCRIBER.FULL_NAME%TYPE      :='Mesut ALTAN'; 
PIS_P_NUMBER     SUBSCRIBER.PHONE_NUMBER%TYPE    :='5554445555';
PIS_E_MAIL       SUBSCRIBER.EMAIL%TYPE           :='mesut.altan@gmail.com'; 
PIS_P_WORD       SUBSCRIBER.PASS_WORD%TYPE       :='Mesut1';
PIS_B_DAY        SUBSCRIBER.BIRTHDATE%TYPE       :='01/07/1998';

BEGIN
    CREATE_USER(PIS_F_NAME, PIS_P_NUMBER, PIS_E_MAIL, PIS_P_WORD, PIS_B_DAY, CHECKER);
END;
/

--GET BALANCES TEST;
DECLARE
PIS_PHONE       SUBSCRIBER_PACKAGE_REMAINDER.PHONE_NUMBER%TYPE    := '5362295555';
REMAIN_GB       SUBSCRIBER_PACKAGE_REMAINDER.DATA_GB_REMAIN%TYPE;
REMAIN_VOICE    SUBSCRIBER_PACKAGE_REMAINDER.VOICE_REMAIN%TYPE;
REMAIN_SMS      SUBSCRIBER_PACKAGE_REMAINDER.SMS_REMAIN%TYPE;
BEGIN
    GET_BALANCES(PIS_PHONE, REMAIN_GB, REMAIN_VOICE, REMAIN_SMS);
END;
/



--SHOW PROFILE TEST;
DECLARE
PIS_PHONE   SUBSCRIBER.PHONE_NUMBER%TYPE :='5362295555';
FNAME       SUBSCRIBER.FULL_NAME%TYPE;
E_MAIL      SUBSCRIBER.EMAIL%TYPE;
PACK_NAME   PACKAGE_CONTENT.PACKAGE_NAME%TYPE;
GB_FULL     PACKAGE_CONTENT.DATA_GB%TYPE;
VOICE_FULL    PACKAGE_CONTENT.VOICE%TYPE;
SMS_FULL    PACKAGE_CONTENT.SMS%TYPE;
BEGIN
    SHOW_PROFILE(PIS_PHONE,FNAME,E_MAIL,PACK_NAME,GB_FULL,VOICE_FULL,SMS_FULL);
END;
/